name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: plutus

      - name: Lint
        run: npm run lint
        working-directory: plutus

      - name: Type check
        run: npm run type-check
        working-directory: plutus

      - name: Run tests
        run: npm run test
        working-directory: plutus

      - name: Build
        run: npm run build
        working-directory: plutus