name: CI

on:
  push:
  pull_request:

jobs:
  plutus-install:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: plutus

  plutus-lint:
    needs: plutus-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: plutus

      - name: Run ESLint
        run: npm run lint
        working-directory: plutus

  plutus-type-check:
    needs: plutus-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: plutus

      - name: Run type-check
        run: npm run type-check
        working-directory: plutus

  plutus-test:
    needs: [ plutus-lint, plutus-type-check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: plutus

      - name: Run tests
        run: npm run test:unit
        working-directory: plutus

  plutus-build:
    needs: [ plutus-lint, plutus-type-check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: plutus

      - name: Build app
        run: npm run build
        working-directory: plutus